# Network for Laravel 11
networks:
  web_network:
    name: laravel11
    driver: bridge
services:
  # PHP App Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel11-app
    container_name: laravel11_app
    restart: always
    volumes:
      - ./src:/var/www/
    networks:
      - web_network
  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: laravel11_mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=laravel11db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
    ports:
      - "3308:3306"
    restart: always
    networks:
      - web_network
  # Nginx Web Server Service
  nginx:
    image: nginx:1.19.8-alpine
    container_name: laravel11_nginx
    volumes:
      - ./src:/var/www
      - ./nginx/conf:/etc/nginx/conf.d
    ports:
      - "8100:80"
    restart: always
    networks:
      - web_network
